if node.chef_environment == 'qa' 
	default['stl-spacewalk']['baseurl'] = "repo.qa.tabajara.intranet"
	default['stl-spacewalk']['server_name'] = "hzspace01.qa.tabajara.intranet"
	default['stl-spacewalk']['activationkey'] = "1-3751bde9c2b0cd25bffba616d8160011"
	default['stl-spacewalk']['interval_rhnsd'] = "240"
	default['stl-spacewalk']['db']['sid'] = "HMLSPACEWALK"
	default['stl-spacewalk']['db']['hostname'] = "hbutanclan01.qa.tabajara.intranet"
	default['stl-spacewalk']['db']['username'] = "spacewalk"
	default['stl-spacewalk']['db']['password'] = "spacewalk"
	default['stl-spacewalk']['ssl']['enable_ssl'] = "Y"
	default['stl-spacewalk']['ssl']['ca_cert_passwd'] = "spacewalk"
	default['stl-spacewalk']['ssl']['renter_ca_cert_passwd'] = "spacewalk"
	default['stl-spacewalk']['ssl']['org'] = "tabajara"
	default['stl-spacewalk']['ssl']['org_unit'] = "QA"
	default['stl-spacewalk']['email'] = "gr_infra@tabajara.com.br"
	default['stl-spacewalk']['ssl']['city'] = "Barueri"
	default['stl-spacewalk']['ssl']['state'] = "SP"
	default['stl-spacewalk']['ssl']['country'] = "BR"
	default['stl-spacewalk']['enable_tftp'] = "Y"
end 
