default['stl-security']['vbnbus1']['prod']['access_log1'] = '/app/log/st_hb_osb/server1_machine1/access.log' 
default['stl-security']['vbnbus1']['prod']['access_log2'] = '/app/log/st_hb_osb/server2_machine1/access.log'
default['stl-security']['vbnbus1']['prod']['access_log3'] = '/app/log/st_hb_osb/server3_machine1/access.log'  
default['stl-security']['vbnbus2']['prod']['access_log1'] = '/app/log/st_hb_osb/server1_machine2/access.log' 
default['stl-security']['vbnbus2']['prod']['access_log2'] = '/app/log/st_hb_osb/server2_machine2/access.log' 
