default['apimonitor']['api'][node.chef_environment]['app_version'] = '1.0.3-1'

default['apimonitor']['api']['prod']['management.endpoint.shutdown.enabled'] = 'false'
default['apimonitor']['api']['prod']['management.endpoints.enabled'] = 'false'
default['apimonitor']['api']['prod']['management.endpoints.health'] = 'true'
default['apimonitor']['api']['prod']['spring.autoconfigure.exclude'] = 'org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration'
default['apimonitor']['api']['prod']['spring.main.banner-mode'] = 'off'
default['apimonitor']['api']['prod']['logging.file'] = '/app/log/standalone/apimonitor/apimonitor.log'
default['apimonitor']['api']['prod']['spring.servlet.multipart.enabled'] = 'true'
default['apimonitor']['api']['prod']['spring.servlet.multipart.file-size-threshold'] = '2KB'
default['apimonitor']['api']['prod']['spring.servlet.multipart.max-file-size'] = '200MB'
default['apimonitor']['api']['prod']['spring.servlet.multipart.max-request-size'] = '215MB' 
default['apimonitor']['api']['prod']['file.upload-dir'] = '/app/standalone'
default['apimonitor']['api']['prod']['debug'] = 'false'
default['apimonitor']['api']['prod']['spring.data.mongodb.database'] = 'LogService'
default['apimonitor']['api']['prod']['spring.data.mongodb.port'] = '27017'
default['apimonitor']['api']['prod']['server.port'] = '8443'
default['apimonitor']['api']['prod']['server.ssl.enabled'] = 'true'
default['apimonitor']['api']['prod']['server.ssl.key-store'] = 'classpath:keystore.p12'
default['apimonitor']['api']['prod']['server.ssl.key-store-password'] = '123456'
default['apimonitor']['api']['prod']['server.ssl.keyStoreType'] = 'PKCS12'
default['apimonitor']['api']['prod']['server.ssl.keyAlias'] = 'tomcat'
default['apimonitor']['api']['prod']['oauth-provider.url'] = 'http://oauth.tabajara.intranet/api'

default['apimonitor']['api']['prod']['user.db'] = 'ApiMonitor'
default['apimonitor']['api']['prod']['passwd'] = 'a7IM0n#u2Er'
default['apimonitor']['api']['prod']['mongo01'] = 'boteco01.tabajara.intranet'
default['apimonitor']['api']['prod']['mongo02'] = 'boteco02.tabajara.intranet'
default['apimonitor']['api']['prod']['mongo03'] = 'boteco03.tabajara.intranet'
default['apimonitor']['api']['prod']['uri'] = 'PrdApiMonitor'

default['apimonitor']['nginx']['prod']['app_name'] = 'apimonitor'
default['apimonitor']['nginx']['prod']['app_port'] = '8443'
default['apimonitor']['nginx']['prod']['server_name'] = 'apimonitor.tabajara.intranet'
