default['stl']['ldap']['usersearchfilter'] = '(sAMAccountName={0})'
default['stl']['ldap']['usersearchbase'] = 'DC=tabajara,DC=corp'
default['stl']['ldap']['groupsearchbase'] = 'OU=SEU_PROJETO,OU=Acesso_Sistemas,OU=Grupos,DC=tabajara,DC=corp'
default['stl']['ldap']['url'] = 'ldap://tabajara.corp'
default['stl']['ldap']['port'] = '3268'
default['stl']['ldap']['dn'] = 'CN=svc_portal,OU=Services,OU=TABAJARA,DC=tabajara,DC=corp'
default['stl']['ldap']['password'] = 'cesar@123'
default['stl']['ldap']['enabled'] = 'true'
