---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: geerlingguy/centos7

suites:
  - name: default
    run_list:
      - recipe[jetty::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:


---
driver:
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]
    - ["private_network", {ip: "192.168.10.1"}]

    